### ISSUE TITLE
Composer package

### ISSUE THREAD

**Issue by XzAeRo** [Netatmo/Netatmo-API-PHP#23]
Would you consider the usage of a Composer package?
I can send a PR with all the needed files and configurations, including the steps that you as a team need to do to properly create a widely available Composer package.

If not, can I suggest a section on your README explaining how to add your project as a composer package? Maybe I can add some example files also.

**Comment by gruberro** [comment]
There are already two open pull requests (#20 and #19) from which at least one is merged soon 😉 .

**Comment by XzAeRo** [comment]
Oh cool, thanks, I didn't bother to check the other PRs. Sorry!
