### ISSUE TITLE
Expired SSL Cert

### ISSUE THREAD

**Issue by livtyler** [Netatmo/Netatmo-API-PHP#32]
Sorry I have tried to contact your support via twitter but I get no reply. This is about the Netatmo Presence Security Camera.

The ssl certificate for wildcard cert *.vpn.neatmo.net has expired which i believe the android and camera use for various purposes. This obviously opens up a possibility to MiTM attacks.

Again sorry for having to inform you on this repo but hopefully you can get it fixed.

**Comment by fpotter92** [comment]
Hi, 

 

This addresses (*.vpn.netatmo.net) have been deprecated and should not be used.

 

Can you please indicate how you’ve come to use it ? The API should (normally) never instruct you to use it…

 

Thanks for your support !

 

fred

 

De : livtyler [mailto:notifications@github.com] 
Envoyé : mardi 23 janvier 2018 16:26
À : Netatmo/Netatmo-API-PHP <Netatmo-API-PHP@noreply.github.com>
Cc : Subscribed <subscribed@noreply.github.com>
Objet : [Netatmo/Netatmo-API-PHP] Expired SSL Cert (#32)

 

Sorry I have tried to contact your support via twitter but I get no reply. This is about the Netatmo Presence Security Camera.

The ssl certificate for wildcard cert *.vpn.neatmo.net has expired which i believe the android and camera use for various purposes. This obviously opens up a possibility to MiTM attacks.

Again sorry for having to inform you on this repo but hopefully you can get it fixed.
