### ISSUE TITLE
Broken links in README

### ISSUE THREAD

**Issue by fox91** [Netatmo/Netatmo-API-PHP#34]
It seems that those links are broken (or redirect to index):

- https://dev.netatmo.com/dev/resources#/technical/reference/weatherstation
- https://dev.netatmo.com/doc/getmeasure
- https://dev.netatmo.com/dev/resources#/technical/reference/thermostat
- https://dev.netatmo.com/dev/resources#/technical/reference/welcome
- https://dev.netatmo.com/dev/resources#/technical/introduction

Can anyone in the stuff sync README links with updated dev links?

**Comment by fabienduval** [comment]
Hi fox91,

thanks for the feedback, the links have been updated.
